# nginx.conf
# Place at /etc/nginx/sites-available/portfolio
# Enable: ln -s /etc/nginx/sites-available/portfolio /etc/nginx/sites-enabled/

server {
    listen 80;
    server_name siddhantdeshpande.com www.siddhantdeshpande.com;

    location / {
        proxy_pass         http://localhost:6767;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}
